package parameters

const ROAD_LEN_THRESHOLD = 30
const ROAD_LEN_THRESHOLD_IN_GETEVENTS = 50.0
const ROAD_RECORD_COUNT_THRESHOLD = 1000

const NEIGHBORING_ROADS_DISTANCE_L = 3000
const NEIGHBORING_ROADS_DISTANCE_S = 500

const CONGESTED_SPEED_THRESHOLD = 15
const CONGESTED_LIMITED_SPEED_THRESHOLD = 20
